### ISSUE TITLE
es_admin and esplugin_mysql

### ISSUE THREAD

**Issue by verfremdet** [kanersps/es_admin#24]
I don't can use es_admin and esplugin_mysql because it's say's it searching for money and bank and thats not in the db

[ERROR] [MySQL] [esplugin_mysql] An error happens on MySQL for query "INSERT INTO users ( (`identifier`, `money`, `bank`, `group`, `permission_level`, `license`) ('steam:11000010c848f9f', 0, 0, 'user', 0 ) .... 
ER_BAD_FIELD_ERROR: Unknown column 'money' in field list'

Please help, when i write the command /admin in the chat this happend: 

SCRIPT ERROR: @es_admin2/server.lua:401: attempt to index a nil value (local 'user')
> ref (@es_admin2/server.lua:401)
> handler (@essentialmode/server/main.lua:205)
> handler (@chat/sv_chat.lua:27)

**Comment by Kretena1** [comment]
Dude I had this error for 5 days, and to end your headache I'm going to help you. By telling you that es_extended ditched essentialmode. So you don't need essentialmode anymore. However, I recommend to use a version before 17 feb. because most scripts are old and don't work with this change. I hope i hepled you.
